# Tracking of a given target.
#
# August 9, 2024

# GOAL
# Camera frame for the tracking
string goal_frame

# Class ID to track
string goal_id

# Desired distance to the target [m]
float64 goal_dist 0.0

# Indicates whether the tracking should stop when the target is aligned
bool stop_when_aligned true

# Indicates if the tracking should start from a specific side
int8 RIGHT=-1
int8 CENTER=0
int8 LEFT=1
int8 start_side 0
---
# RESULT
# Operation result
dua_common_interfaces/CommandResultStamped result
---
# FEEDBACK
