# Autonomous robot information.
#
# July 30, 2026

# UUID of the agent
uint64 ag_uuid

# Human-readable name of the agent
string ag_name

# Agent type
dua_mission_interfaces/AgentType ag_type

# Agent zenohd configuration
dua_mission_interfaces/AgentZenohdConf ag_zenohd_conf

# Agent topics
dua_mission_interfaces/AgentTopics ag_topics

# Agent capabilities
dua_mission_interfaces/AgentCapabilities ag_capabilities
